<?php

namespace AppBundle\Repository;

/**
 * PruebasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebasRepository extends \Doctrine\ORM\EntityRepository
{
}
